services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/url_shortener?sslmode=disable
      PORT: "8080"
    ports:
      - "8080:8080"